### PR TITLE
Filter bug fix

### LINKED ISSUE #217: Add a filter to the list component
Add a filter to the list component. It should take a function as an input and that function will be run against the items in the list to decide what's shown. 

Some edge cases might need to be handled like if the filter is invalid and breaks when run... or if the list has no items after filtering how will we display that?

### PR DESCRIPTION
**Pull request by AdiMakkar**
closes #217

### CODE REVIEW

**Comment by AdiMakkar** [comment]
Linter caught me with two issues in list.component.ts. The functionality behind the filtering is in place. Fixing the linter issues.

**Review by doug0102 — COMMENTED** [review]
Where is the filtering? I don't see a filter happening anywhere. It looks like you just created an array for upcoming and previous events but are not filtering anything... unless I'm missing something?

**Comment by AdiMakkar** [comment]
lint issues updated, waiting on a code review from @doug0102 to verify list.component.ts changes don't break any thing

File: src/app/shared/components/list/list.component.ts [hunk 1]
```diff
@@ -22,31 +22,31 @@ export class ListComponent implements OnInit {
...
-  loadNext(count: number = this.pageSize): void {
+  loadNext(_count: number = this.pageSize): void {
     this.loading = true;
 
-    this.service?.getMany(count, this.loadTime).subscribe((items: (typeof this.service.dataType)[]) => {
+    this.service?.getMany(_count, this.loadTime).subscribe((items: (typeof this['service']['dataType'])[]) => {
       this.items.push(...items);
-      this.lastPage = this.items.length / this.pageSize;
-      this.loading = false;
+      this.lastPage = Math.ceil(this.items.length / this.pageSize);
```
Comment (doug0102) [inline src/app/shared/components/list/list.component.ts:48]: good catch

File: src/app/shared/components/list/list.component.ts [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import { Component, Input, OnInit } from '@angular/core';
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
-import { NgComponentOutlet } from '@angular/common';
+// import { NgComponentOutlet } from '@angular/common';
```
Comment (doug0102) [inline src/app/shared/components/list/list.component.ts:3]: This is weird it's not throwing an error. I thought I had to import this to use the ngComponentOutlet in the template, but it seems to be working.

File: src/app/shared/components/list/list.component.ts [hunk 3]
```diff
@@ -11,8 +11,8 @@ import { Orientation } from '../../models/orientation';
   styleUrls: ['./list.component.scss'],
 })
 export class ListComponent implements OnInit {
-  @Input({ required: true }) service!: IListService;
-  @Input() items: (typeof this.service.dataType)[] = [];
+  @Input() service!: IListService;
+  @Input() items: (typeof this['service']['dataType'])[] = [];
```
Comment (doug0102) [inline src/app/shared/components/list/list.component.ts:15]: Did the linter complain about formatting it as `this.service.dataType`? It didn't complain about that before which is weird.

**Review by doug0102 — APPROVED** [review]

File: src/app/shared/components/list/list.component.ts (hunk 1 above)
Comment (AdiMakkar) [reply src/app/shared/components/list/list.component.ts:48]: yep I figured I use Math.ceil because it didn't make sense to me.

File: src/app/shared/components/list/list.component.ts (hunk 2 above)
Comment (AdiMakkar) [reply src/app/shared/components/list/list.component.ts:3]: Yep, it's not being used which like you said is weird. but works haha

File: src/app/shared/components/list/list.component.ts (hunk 3 above)
Comment (AdiMakkar) [reply src/app/shared/components/list/list.component.ts:15]: Nope, I was surprised on that too.
